CREATE TABLE "GCG_5169_CopyLinks"(
 "Quote_Order_No" CHAR(7) NOT NULL ,
 "Trans_Type" CHAR(2) NOT NULL ,
 "Notes" LONGVARCHAR,
 "CREATED_USER" VARCHAR(8),
 "CREATED_DATE" DATETIME,
 "LAST_CHG_USER" VARCHAR(8),
 "LAST_CHG_DATE" DATETIME,
 PRIMARY KEY ("Quote_Order_No", "Trans_Type"));